name: Quarto Publish

on:
  push:
    branches:
      - main  # Change to your branch if necessary

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 2  # Ensure we fetch more commits if needed

      # Step 2: Setup Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: '1.3.433'  # Use a stable version of Quarto

      # Step 3: Install R (if using R in Quarto files)
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      # Step 4: Render all .qmd files
      - name: Render Quarto documents
        run: |
          mkdir -p _site  # Ensure the _site directory exists
          find . -name "*.qmd" -print0 | while IFS= read -r -d '' file; do
            echo "Rendering $file"
            quarto render "$file"
          done

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # Directory where the rendered HTML will be placed
