name: Quarto Publish

on:
  push:
    branches:
      - main  # This will trigger the workflow on changes to the "main" branch

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Setup Quarto
      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 'latest'

      # Step 3: Install R (if using R in Quarto files)
      - name: Setup R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'latest'

      # Step 4: Render the Quarto project
      - name: Render Quarto site
        run: quarto render

      # Step 5: Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site  # This is where the rendered HTML will be placed
